export enum AsaasWebhookEventEnum {
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_OVERDUE = 'PAYMENT_OVERDUE',
  SUBSCRIPTION_INACTIVATED = 'SUBSCRIPTION_INACTIVATED',
  SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED',
}
